### ISSUE TITLE
Document Not Defined - Lottie

### ISSUE THREAD

**Issue by ArlinJae** [zenorocha/zenorocha.com#66]
Hi @zenorocha, seemed to be getting this error while deploying locally (doesn't seem to be a problem while working on vercel).

```
ReferenceError: document is not defined
    at createTag (/Users/ArlinJae/Documents/website/node_modules/lottie-web/build/player/lottie.js:30:5)
    at /Users/ArlinJae/Documents/website/node_modules/lottie-web/build/player/lottie.js:1309:20
    at /Users/ArlinJae/Documents/website/node_modules/lottie-web/build/player/lottie.js:1316:6
    at /Users/ArlinJae/Documents/website/node_modules/lottie-web/build/player/lottie.js:1533:4
    at /Users/ArlinJae/Documents/website/node_modules/lottie-web/build/player/lottie.js:2:83
    at Object.<anonymous> (/Users/ArlinJae/Documents/website/node_modules/lottie-web/build/player/lottie.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  type: 'ReferenceError'
}
```

Any clue on where I'm going wrong?

**Comment by anoopsonar30** [comment]
I ran into the same issue. I rolled my nodejs installed back to 18.x and that fixed it.
